import pytest

from auth.oauth21_session_store import OAuth21SessionStore
from auth.oauth_state_store import OAuthStateStore, _deserialize_state_entry


# OAuth state tokens must be lowercase hex strings (as generated by os.urandom(16).hex()).
_STATE_SHARED = "aabbccddeeff0011"
_STATE_LATEST = "1122334455667788"
_STATE_NONE = "cafebabecafebabe"
_STATE_SESSION1 = "deadbeefdeadbeef"


def test_oauth_state_persists_across_store_instances(tmp_path):
    """State written by one store instance is readable by another (simulates replica swap)."""
    state_dir = str(tmp_path / "oauth_states")
    store_a = OAuth21SessionStore(oauth_state_dir=state_dir)
    store_b = OAuth21SessionStore(oauth_state_dir=state_dir)

    store_a.store_oauth_state(
        _STATE_SHARED,
        session_id="session-123",
        code_verifier="verifier-123",
    )

    state_info = store_b.validate_and_consume_oauth_state(
        _STATE_SHARED,
        session_id="session-123",
    )

    assert state_info["session_id"] == "session-123"
    assert state_info["code_verifier"] == "verifier-123"


def test_consume_latest_oauth_state_reads_from_shared_dir(tmp_path):
    """consume_latest crosses store instances (simulates stdio fallback on restart)."""
    state_dir = str(tmp_path / "oauth_states")
    store_a = OAuth21SessionStore(oauth_state_dir=state_dir)
    store_b = OAuth21SessionStore(oauth_state_dir=state_dir)

    store_a.store_oauth_state(
        _STATE_LATEST,
        session_id=None,
        code_verifier="latest-verifier",
    )

    state_info = store_b.consume_latest_oauth_state()

    assert state_info is not None
    assert state_info["code_verifier"] == "latest-verifier"
    # Consuming it removed the file; second call returns None
    assert store_a.consume_latest_oauth_state() is None


def test_consume_latest_oauth_state_filters_by_initiating_session_id(tmp_path):
    state_dir = str(tmp_path / "oauth_states")
    store_a = OAuth21SessionStore(oauth_state_dir=state_dir)
    store_b = OAuth21SessionStore(oauth_state_dir=state_dir)

    store_a.store_oauth_state(
        _STATE_NONE,
        session_id=None,
        code_verifier="verifier-none",
    )
    store_a.store_oauth_state(
        _STATE_SESSION1,
        session_id="session-1",
        code_verifier="verifier-session-1",
    )

    state_info = store_b.consume_latest_oauth_state(initiating_session_id="session-1")

    assert state_info is not None
    assert state_info["session_id"] == "session-1"
    assert state_info["code_verifier"] == "verifier-session-1"

    remaining_state_info = store_a.consume_latest_oauth_state(
        initiating_session_id=None
    )
    assert remaining_state_info is not None
    assert remaining_state_info["session_id"] is None
    assert remaining_state_info["code_verifier"] == "verifier-none"


def test_deserialize_state_entry_normalizes_invalid_and_naive_timestamps():
    """_deserialize_state_entry in oauth_state_store handles bad/naive timestamps."""
    deserialized = _deserialize_state_entry(
        {
            "created_at": "2026-04-21T12:00:00",
            "expires_at": "not-a-timestamp",
            "session_id": "session-123",
        }
    )

    assert deserialized["created_at"] is not None
    assert deserialized["created_at"].tzinfo is not None
    assert deserialized["expires_at"] is None


def test_state_cannot_be_consumed_twice(tmp_path):
    """Replay protection: a state is deleted on first consume."""
    state_dir = str(tmp_path / "oauth_states")
    store = OAuth21SessionStore(oauth_state_dir=state_dir)

    store.store_oauth_state(_STATE_SHARED, code_verifier="cv")
    store.validate_and_consume_oauth_state(_STATE_SHARED)

    with pytest.raises(ValueError, match="Invalid or expired OAuth state parameter"):
        store.validate_and_consume_oauth_state(_STATE_SHARED)


def test_store_session_rejects_mcp_session_rebind_by_default(tmp_path):
    state_dir = str(tmp_path / "oauth_states")
    store = OAuth21SessionStore(oauth_state_dir=state_dir)

    store.store_session(
        user_email="account-a@example.com",
        access_token="token-a",
        mcp_session_id="session-123",
    )

    with pytest.raises(ValueError, match="already bound to a different user"):
        store.store_session(
            user_email="account-b@example.com",
            access_token="token-b",
            mcp_session_id="session-123",
        )


def test_store_session_skips_mcp_binding_in_single_user_mode(tmp_path, monkeypatch):
    monkeypatch.setenv("MCP_SINGLE_USER_MODE", "1")

    state_dir = str(tmp_path / "oauth_states")
    store = OAuth21SessionStore(oauth_state_dir=state_dir)

    store.store_session(
        user_email="account-a@example.com",
        access_token="token-a",
        mcp_session_id="session-123",
    )
    store.store_session(
        user_email="account-b@example.com",
        access_token="token-b",
        mcp_session_id="session-123",
    )

    assert store.get_user_by_mcp_session("session-123") is None
    assert store.get_credentials("account-b@example.com").token == "token-b"
