"""
Persistent OAuth State Store

Stores one JSON file per OAuth state in a subdirectory of the credentials
directory, using atomic rename writes so that container restarts and Railway
volume remounts don't lose in-flight OAuth states.

Why per-file instead of a single shared JSON file
--------------------------------------------------
The original oauth_states.json approach used fcntl.flock for cross-process
safety.  fcntl advisory locks are not reliably honoured on all network
filesystems that Railway may use for volumes.  More importantly, a write to a
single shared file from two concurrent processes creates a torn-write window
even with locking if the process is killed mid-write.

Per-file storage solves both problems:
- Each state is an independent file.  Concurrent auth flows write to
  different filenames, so there is never a write conflict.
- Atomic rename (write to <id>.tmp, then os.rename) gives crash-safety
  even on NFS: the rename is a single syscall and is atomic on POSIX
  filesystems.  On non-POSIX volumes (unlikely on Railway) the worst case
  is a stale .tmp file, never a half-written state file.

Security note
-------------
State files contain the PKCE code_verifier.  They do NOT contain access
tokens, refresh tokens, or id_tokens.  Those live in the credential store.
The state file is only needed for the duration of the consent-redirect dance
(default TTL: 10 minutes).
"""

import json
import logging
import os
import tempfile
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

# Default TTL matches the industry-standard OAuth authorization code window.
DEFAULT_STATE_TTL_SECONDS = 600  # 10 minutes


def _get_default_state_dir() -> str:
    """Resolve the OAuth state directory from the environment.

    Priority:
    1. WORKSPACE_MCP_OAUTH_STATE_DIR        (explicit override)
    2. <WORKSPACE_MCP_CREDENTIALS_DIR>/oauth_states/
    3. <GOOGLE_MCP_CREDENTIALS_DIR>/oauth_states/  (backward compat)
    4. ~/.google_workspace_mcp/credentials/oauth_states/
    5. ./.credentials/oauth_states/          (last-resort fallback)
    """
    explicit = os.getenv("WORKSPACE_MCP_OAUTH_STATE_DIR")
    if explicit:
        return os.path.expanduser(explicit)

    workspace_creds = os.getenv("WORKSPACE_MCP_CREDENTIALS_DIR")
    if workspace_creds:
        return os.path.join(os.path.expanduser(workspace_creds), "oauth_states")

    google_creds = os.getenv("GOOGLE_MCP_CREDENTIALS_DIR")
    if google_creds:
        return os.path.join(os.path.expanduser(google_creds), "oauth_states")

    home = os.path.expanduser("~")
    if home and home != "~":
        return os.path.join(home, ".google_workspace_mcp", "credentials", "oauth_states")

    return os.path.join(os.getcwd(), ".credentials", "oauth_states")


def _ensure_state_dir(state_dir: str) -> None:
    """Create the state directory with restrictive permissions if it doesn't exist."""
    os.makedirs(state_dir, mode=0o700, exist_ok=True)
    try:
        os.chmod(state_dir, 0o700)
    except OSError:
        logger.debug("Could not chmod OAuth state directory %s", state_dir)


def _state_file_path(state: str, state_dir: str) -> str:
    """Return the path for a state file.

    The state parameter is already a random hex string generated by
    ``os.urandom(16).hex()``, so it is safe to use directly as a filename.
    We validate it here as an extra defence-in-depth measure.
    """
    if not state or not all(c in "0123456789abcdefABCDEF" for c in state):
        raise ValueError(f"OAuth state contains unexpected characters: {state!r}")
    return os.path.join(state_dir, f"{state}.json")


def _serialize_state_entry(state_info: Dict[str, Any]) -> Dict[str, Any]:
    """Prepare a state info dict for JSON serialisation."""
    out: Dict[str, Any] = {}
    for key, value in state_info.items():
        if isinstance(value, datetime):
            aware = value if value.tzinfo else value.replace(tzinfo=timezone.utc)
            out[key] = aware.astimezone(timezone.utc).isoformat()
        else:
            out[key] = value
    return out


def _deserialize_state_entry(raw: Dict[str, Any]) -> Dict[str, Any]:
    """Parse a JSON-loaded dict back to a state info dict with datetime fields."""
    result = dict(raw)
    for field in ("created_at", "expires_at"):
        raw_value = result.get(field)
        if isinstance(raw_value, str):
            try:
                parsed = datetime.fromisoformat(raw_value.replace("Z", "+00:00"))
                if parsed.tzinfo is None:
                    parsed = parsed.replace(tzinfo=timezone.utc)
                result[field] = parsed
            except (TypeError, ValueError):
                result[field] = None
    return result


class OAuthStateStore:
    """Persistent, per-file OAuth state store backed by a directory on disk.

    Each active OAuth flow produces exactly one file:
        <state_dir>/<hex_state_id>.json

    Writes use atomic rename to avoid torn writes.  Reads are plain open+parse.
    No locking is needed because state IDs are randomly generated and unique
    per flow; two concurrent flows never write to the same filename.

    Expired state files are cleaned up opportunistically on each write (i.e.
    each time a new auth flow is started).  A missed cleanup leaves a small
    stale file that will be ignored on the next read attempt.
    """

    def __init__(self, state_dir: Optional[str] = None) -> None:
        self._state_dir: str = state_dir or _get_default_state_dir()

    # ------------------------------------------------------------------
    # Public API (mirrors the surface consumed by OAuth21SessionStore)
    # ------------------------------------------------------------------

    def store(
        self,
        state: str,
        session_id: Optional[str] = None,
        code_verifier: Optional[str] = None,
        redirect_uri: Optional[str] = None,
        user_google_email: Optional[str] = None,
        expires_in_seconds: int = DEFAULT_STATE_TTL_SECONDS,
    ) -> None:
        """Persist an OAuth state entry atomically.

        Parameters match the fields that ``OAuth21SessionStore.store_oauth_state``
        stores, extended with ``redirect_uri`` and ``user_google_email`` for
        completeness.  Extra keyword arguments are ignored for forward compat.

        Security: code_verifier is written to the state file.  Access tokens
        and refresh tokens are NEVER stored here.
        """
        if not state:
            raise ValueError("OAuth state must be a non-empty string")
        if expires_in_seconds < 0:
            raise ValueError("expires_in_seconds must be non-negative")

        _ensure_state_dir(self._state_dir)
        self._cleanup_expired()

        now = datetime.now(timezone.utc)
        state_info: Dict[str, Any] = {
            "session_id": session_id,
            "code_verifier": code_verifier,
            "redirect_uri": redirect_uri,
            "user_google_email": user_google_email,
            "created_at": now,
            "expires_at": now + timedelta(seconds=expires_in_seconds),
        }

        self._write_atomic(state, state_info)
        logger.debug(
            "Stored OAuth state %s (expires in %ds)",
            state[:8] if len(state) > 8 else state,
            expires_in_seconds,
        )

    def consume(self, state: str) -> Optional[Dict[str, Any]]:
        """Read, validate TTL, and delete a state entry atomically.

        Returns the state info dict on success, or None if the state is
        missing or expired.  The file is removed regardless of expiry so
        expired files are also cleaned up here.
        """
        if not state:
            return None

        try:
            state_path = _state_file_path(state, self._state_dir)
        except ValueError:
            logger.warning("consume: invalid state token format")
            return None

        if not os.path.exists(state_path):
            return None

        try:
            with open(state_path, "r", encoding="utf-8") as fh:
                raw = fh.read()
        except OSError as exc:
            logger.debug("Could not read state file %s: %s", state_path, exc)
            return None

        try:
            payload = json.loads(raw)
        except json.JSONDecodeError as exc:
            logger.warning("Corrupt state file %s: %s — removing", state_path, exc)
            self._safe_remove(state_path)
            return None

        state_info = _deserialize_state_entry(payload)

        expires_at = state_info.get("expires_at")
        if expires_at and datetime.now(timezone.utc) >= expires_at:
            logger.debug(
                "OAuth state %s expired at %s — removing",
                state[:8] if len(state) > 8 else state,
                expires_at.isoformat(),
            )
            self._safe_remove(state_path)
            return None

        # Consume: remove file before returning so the state can't be reused.
        self._safe_remove(state_path)

        logger.debug(
            "Consumed OAuth state %s",
            state[:8] if len(state) > 8 else state,
        )
        return state_info

    def consume_latest(
        self, session_id: Optional[str] = None
    ) -> Optional[Dict[str, Any]]:
        """Consume and return the most recently created non-expired state.

        Optionally filter by ``session_id``.  Used as a stdio fallback when
        Google omits the state parameter from the redirect.

        Returns None if no matching state exists.
        """
        if not os.path.isdir(self._state_dir):
            return None

        candidates: list[tuple[datetime, str, Dict[str, Any]]] = []
        now = datetime.now(timezone.utc)

        try:
            filenames = os.listdir(self._state_dir)
        except OSError as exc:
            logger.debug("Could not list state dir: %s", exc)
            return None

        for filename in filenames:
            if not filename.endswith(".json") or filename.endswith(".tmp"):
                continue
            state_id = filename[:-5]  # strip .json
            state_path = os.path.join(self._state_dir, filename)
            try:
                with open(state_path, "r", encoding="utf-8") as fh:
                    raw = fh.read()
            except OSError:
                continue
            try:
                payload = json.loads(raw)
            except json.JSONDecodeError:
                continue

            entry = _deserialize_state_entry(payload)
            expires_at = entry.get("expires_at")
            if expires_at and now >= expires_at:
                self._safe_remove(state_path)
                continue

            # Filter by session_id when provided
            if session_id is not None and entry.get("session_id") != session_id:
                continue

            created_at = entry.get("created_at") or datetime.min.replace(
                tzinfo=timezone.utc
            )
            candidates.append((created_at, state_id, entry))

        if not candidates:
            return None

        # Pick the most recently created candidate.
        candidates.sort(key=lambda t: t[0], reverse=True)
        _, best_state_id, best_entry = candidates[0]

        # Consume the winner — route through _state_file_path so the same
        # hex whitelist validation applied in consume() covers this path too.
        try:
            best_path = _state_file_path(best_state_id, self._state_dir)
        except ValueError:
            logger.warning(
                "consume_latest: best candidate has invalid state ID format %r — skipping",
                best_state_id[:8] if len(best_state_id) > 8 else best_state_id,
            )
            return None
        self._safe_remove(best_path)

        logger.debug(
            "Consumed latest OAuth state %s as stdio fallback",
            best_state_id[:8] if len(best_state_id) > 8 else best_state_id,
        )
        return best_entry

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _write_atomic(self, state: str, state_info: Dict[str, Any]) -> None:
        """Write state_info to a .tmp file then rename it into place."""
        state_path = _state_file_path(state, self._state_dir)
        payload = json.dumps(_serialize_state_entry(state_info), indent=2, sort_keys=True)

        # Write to a temp file in the same directory so rename is atomic.
        fd, tmp_path = tempfile.mkstemp(
            suffix=".tmp", prefix=f"{state[:8]}_", dir=self._state_dir
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(payload)
                fh.flush()
                os.fsync(fh.fileno())
            try:
                os.chmod(tmp_path, 0o600)
            except OSError:
                logger.debug("Could not chmod tmp state file %s", tmp_path)
            os.rename(tmp_path, state_path)
        except Exception:
            # Best-effort cleanup of the tmp file on failure.
            try:
                os.unlink(tmp_path)
            except OSError:
                pass
            raise

    def _cleanup_expired(self) -> None:
        """Remove expired state files.  Called on each write; best-effort."""
        if not os.path.isdir(self._state_dir):
            return
        now = datetime.now(timezone.utc)
        try:
            filenames = os.listdir(self._state_dir)
        except OSError:
            return
        for filename in filenames:
            if not filename.endswith(".json") or filename.endswith(".tmp"):
                continue
            state_id = filename[:-5]  # strip .json
            # Route through _state_file_path for the same hex whitelist
            # validation used on all other deletion paths (F-001 consistency fix).
            try:
                state_path = _state_file_path(state_id, self._state_dir)
            except ValueError:
                logger.debug(
                    "_cleanup_expired: skipping file with invalid name %r", filename
                )
                continue
            try:
                with open(state_path, "r", encoding="utf-8") as fh:
                    payload = json.loads(fh.read())
                entry = _deserialize_state_entry(payload)
                expires_at = entry.get("expires_at")
                if expires_at and now >= expires_at:
                    self._safe_remove(state_path)
                    logger.debug("Cleaned up expired state file %s", filename)
            except (OSError, json.JSONDecodeError, KeyError):
                pass  # leave malformed files; they'll be cleaned next time

    @staticmethod
    def _safe_remove(path: str) -> None:
        """Remove a file, suppressing errors if it's already gone."""
        try:
            os.unlink(path)
        except FileNotFoundError:
            pass
        except OSError as exc:
            logger.debug("Could not remove state file %s: %s", path, exc)


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

_store: Optional[OAuthStateStore] = None


def get_oauth_state_store() -> OAuthStateStore:
    """Return the module-level singleton OAuthStateStore."""
    global _store
    if _store is None:
        _store = OAuthStateStore()
    return _store
